### PR TITLE
Accurate turning and distance by implementing PID

### PR DESCRIPTION
**Pull request by julianalg**

### CODE REVIEW

**Comment by julianalg** [comment]
/Users/julianalg/Desktop/MarauderTech/FRC Crescendo 2024/2024-crescendo/src/main/java/frc/robot/subsystems/DriveSubsystem.java:72: warning: [removal] CANSparkMax(int,MotorType) in CANSparkMax has been deprecated and marked for removal
        rightRear = new CANSparkMax(kRightRearID, MotorType.kBrushed);
                    ^
9 warnings 

not super important but still weird

**Comment by julianalg** [comment]
pending on the encoders being installed in the gearbox

**Comment by rake6682** [comment]
So uh..... it doesn't work. it could be a no encoder issue, time to troubleshoot

**Comment by julianalg** [comment]
this needs encoders to work, so if it's not working without encoders that's why

**Comment by julianalg** [comment]
never mind, the Spark Max controllers should have built in encoders but i think in the code im trying to read from nonexistent controllers

**Comment by 9573maraudertech** [comment]
see SysID

**Pull request closed without merging**
